//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DBFirstApproachDemo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int id { get; set; }
        [DisplayName("Product Name")]
        [Required(ErrorMessage ="Product name is required!")]
        public string Name { get; set; }


        [DisplayName("Product Image")]
        public string FilePath { get; set; }


        [DisplayName("Product Price")]
        [Required(ErrorMessage = "Product price is required!")]

        public decimal Price { get; set; }

        [DisplayName("Product Description")]
        [Required(ErrorMessage = "Product description is required!")]

        public string Description { get; set; }

        [DisplayName("Product Storage")]
        [Required(ErrorMessage = "Product storage is required!")]

        public string storage { get; set; }

        [DisplayName("Product Category")]
        [Required(ErrorMessage = "Product category is required!")]

        public int Category_id { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime update_date { get; set; }
        
        public HttpPostedFileBase ImageFile { get; set; }   
        public virtual Category Category { get; set; }
        public Product() { 
            create_date=DateTime.Now;
            update_date = create_date;
        }
    }
}
